import React from "react";
import { StyleSheet, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { COLORS } from "@/src/theme";
import { Card } from "@/src/components/ui";
import HoldProgressButton from "@/src/components/HoldProgressButton";

export default function NotificationStreakCard({ score, target, notificationStreak, dailyStreak, maxDailyStreak, onHoldDone, onDailyPress }: { score:number; target:number; notificationStreak:number; dailyStreak:number; maxDailyStreak:number; onHoldDone:()=>void; onDailyPress:()=>void }) {
  const percent=target>0?Math.min(100,Math.round(score/target*100)):0; const milestone=percent>=100?"Sacred target complete":percent>=75?"Final ascent":percent>=50?"Momentum unlocked":percent>=25?"Foundation strong":"Build your first spark";
  return <Card testID="streak-hub-card" style={styles.card}><LinearGradient colors={[COLORS.electric+"24",COLORS.surface1]} style={StyleSheet.absoluteFillObject}/><View style={styles.header}><View><Text style={styles.eyebrow}>STREAK HUB</Text><Text style={styles.title}>Notification Streak</Text></View><View style={styles.scorePill} testID="notification-streak-score"><Text style={styles.score}>{score}/{target}</Text></View></View><View style={styles.progressTrack} testID="notification-streak-progress"><View style={[styles.progressFill,{width:`${percent}%`}]} /></View><View style={styles.meta}><Text style={styles.percent}>{percent}%</Text><Text style={styles.milestone}>{milestone}</Text><Text style={styles.dayStreak}>{notificationStreak} day response streak</Text></View><HoldProgressButton testID="notification-streak-hold-done" label="HOLD TO MARK DONE" onComplete={onHoldDone} color={COLORS.electric} style={{marginTop:16}}/><View style={styles.divider}/><View style={styles.dailyRow} testID="daily-streak-summary"><View style={styles.flame}><Ionicons name="flame" size={24} color={COLORS.gold}/></View><View style={{flex:1}}><Text style={styles.dailyTitle}>Daily Ritual Streak</Text><Text style={styles.dailySub}>{dailyStreak} days · Personal best {maxDailyStreak}</Text></View><Text onPress={onDailyPress} testID="daily-streak-details" style={styles.details}>Details</Text></View></Card>;
}

const styles=StyleSheet.create({card:{padding:20,overflow:"hidden",borderWidth:1,borderColor:COLORS.electric+"44"},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},eyebrow:{color:COLORS.electric,fontSize:10,fontWeight:"900",letterSpacing:1.8},title:{color:COLORS.white,fontSize:21,fontWeight:"900",marginTop:3},scorePill:{backgroundColor:COLORS.electric+"25",borderRadius:999,paddingHorizontal:12,paddingVertical:7},score:{color:COLORS.white,fontSize:15,fontWeight:"900"},progressTrack:{height:12,borderRadius:999,backgroundColor:COLORS.surface2,overflow:"hidden",marginTop:18},progressFill:{height:"100%",borderRadius:999,backgroundColor:COLORS.electric},meta:{flexDirection:"row",alignItems:"center",gap:9,marginTop:9,flexWrap:"wrap"},percent:{color:COLORS.electric,fontSize:12,fontWeight:"900"},milestone:{color:COLORS.white,fontSize:12,fontWeight:"800"},dayStreak:{color:COLORS.gray1,fontSize:11.5},divider:{height:1,backgroundColor:COLORS.gray3,marginVertical:18},dailyRow:{minHeight:50,flexDirection:"row",alignItems:"center",gap:12},flame:{width:44,height:44,borderRadius:14,backgroundColor:COLORS.gold+"18",alignItems:"center",justifyContent:"center"},dailyTitle:{color:COLORS.white,fontSize:15,fontWeight:"900"},dailySub:{color:COLORS.gray1,fontSize:11.5,marginTop:3},details:{color:COLORS.gold,fontSize:12,fontWeight:"800",paddingVertical:14}});